### ISSUE TITLE
PlatformException Attempt to invoke virtual method 'void android.app.Activity.setRequestedOrientation(int)' on a null object reference

### ISSUE THREAD

**Issue by rayliverified** [bytepark/auto_orientation#23]
This error is thrown very often on orientation change.
```
PlatformException(error, Attempt to invoke virtual method 'void android.app.Activity.setRequestedOrientation(int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.setRequestedOrientation(int)' on a null object reference
	at de.bytepark.autoorientation.AutoOrientationPlugin.onMethodCall(AutoOrientationPlugin.java:50)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by fbatschi** [comment]
@searchy2 Do you have any example application code to better understand the behavior you are talking about?

**Comment by rayliverified** [comment]
Let me see if I'm still seeing the issue! If so, would you like me to share a sample project?

**Comment by fbatschi** [comment]
yes if possible, as i cant reproduce that right now

**Comment by rayliverified** [comment]
Not seeing this error anymore! 
Thank you!
